### ISSUE TITLE
get_documents fails with BTGlobalTreeNodeInfo has no key 'defaultElementId' 

### ISSUE THREAD

**Issue by pmdhazy** [onshape-public/onshape-clients#22]
The following call:
> client = Client()
results = client.documents_api.get_documents(q="FlatTest1")
print(results)

fails with BTGlobalTreeNodeInfo has no key 'defaultElementId' 

This was using onshape_client version 1.2.0 (also failed on 1.1.0)

> (env3) [leotest@leotest-2 leo]$ ./get_doc_bug1.py
Traceback (most recent call last):
  File "./get_doc_bug1.py", line 25, in <module>
    q=name,
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/api/documents_api.py", line 2920, in __call__
    return self.callable(self, *args, **kwargs)
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/api/documents_api.py", line 1382, in __get_documents
    return self.call_with_http_info(**kwargs)
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/api/documents_api.py", line 2994, in call_with_http_info
    collection_formats=params["collection_format"],
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/api_client.py", line 383, in call_api
    _check_type,
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/api_client.py", line 202, in __call_api
    response_data, response_type, _check_type
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/api_client.py", line 295, in deserialize
    configuration=self.configuration,
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 1072, in validate_and_convert_types
    must_convert=True,
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 1002, in attempt_convert_item
    raise conversion_exc
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 995, in attempt_convert_item
    from_server,
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 851, in deserialize_model
    instance = used_model_class(**kw_args)
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/models/bt_global_tree_node_list_response.py", line 141, in __init__
    setattr(self, var_name, var_value)
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 186, in __setattr__
    self.set_attribute(name, value)
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 89, in set_attribute
    configuration=self._configuration,
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 1119, in validate_and_convert_types
    configuration=configuration,
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 1072, in validate_and_convert_types
    must_convert=True,
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 1002, in attempt_convert_item
    raise conversion_exc
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 995, in attempt_convert_item
    from_server,
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 851, in deserialize_model
    instance = used_model_class(**kw_args)
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/models/bt_global_tree_node_info.py", line 241, in __init__
    setattr(self, var_name, var_value)
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 186, in __setattr__
    self.set_attribute(name, value)
  File "/users/leotest/env3/lib/python3.6/site-packages/onshape_client/oas/model_utils.py", line 62, in set_attribute
    "{0} has no key '{1}'".format(type(self).__name__, name), path_to_item
onshape_client.oas.exceptions.ApiKeyError: "BTGlobalTreeNodeInfo has no key 'defaultElementId' at ['received_data']['items'][0]['defaultElementId']"

**Comment by runfalk** [comment]
Can confirm this issue. It happens event without providing any parameters: `c.documents_api.get_documents()`

**Comment by ethan92429** [comment]
Thanks for finding this. It has to do with the generated models not matching the response from the server. I'm currently building a patch with the updated openapi spec. I will post back here when it is ready and in master.

**Comment by runfalk** [comment]
Can confirm that this is fixed in version 1.3.0.

**Comment by ethan92429** [comment]
Thanks!
