### ISSUE TITLE
urllib3: LocationValueError("No host specified.") when instantiating ConfiguredOnshapeElement

### ISSUE THREAD

**Issue by oliver-leung** [onshape-public/onshape-clients#9]
I'm trying to instantiate a `ConfiguredOnshapeElement` from a URL according to [these instructions](https://ethan92429.github.io/onshape-clients/python_html/make_configuration_url.html), but I'm getting an error while doing so.

I have `onshape-client==0.0.25` installed, and `~/.onshape_client_config.yaml` set as follows:
```yaml
prod-api_keys:
  baseUrl: 'https://cad.onshape.com'
  access_key: (my access key)
  secret_key: (my secret key)
prod-oauth:
  baseUrl: 'https://cad.onshape.com'
default_stack: prod-api_keys
```

I try running the following code:
```python
>>> from onshape_client.client import Client
>>> from onshape_client.onshape_url import ConfiguredOnshapeElement
>>> url = "https://cad.onshape.com/documents/cca81d10f239db0db9481e6f/v/aaa25d18038e06f0b2964e2d/e/69c9eedda86512966b20bc90"
>>> element = ConfiguredOnshapeElement(url)
```

This results in the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oliver/.local/lib/python3.6/site-packages/onshape_client/onshape_url.py", line 73, in __init__
    self._raw_configuration_params = self._get_raw_configuration_params()
  File "/home/oliver/.local/lib/python3.6/site-packages/onshape_client/onshape_url.py", line 156, in _get_raw_configuration_params
    _preload_content=False)
  File "/home/oliver/.local/lib/python3.6/site-packages/onshape_client/api/elements_api.py", line 541, in get_configuration3
    (data) = self.get_configuration3_with_http_info(did, wvm, wvmid, eid, **kwargs)  # noqa: E501
  File "/home/oliver/.local/lib/python3.6/site-packages/onshape_client/api/elements_api.py", line 636, in get_configuration3_with_http_info
    collection_formats=collection_formats)
  File "/home/oliver/.local/lib/python3.6/site-packages/onshape_client/api_client.py", line 337, in call_api
    _preload_content, _request_timeout)
  File "/home/oliver/.local/lib/python3.6/site-packages/onshape_client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/home/oliver/.local/lib/python3.6/site-packages/onshape_client/api_client.py", line 358, in request
    headers=headers)
  File "/home/oliver/.local/lib/python3.6/site-packages/onshape_client/rest.py", line 292, in GET
    query_params=query_params)
  File "/home/oliver/.local/lib/python3.6/site-packages/onshape_client/rest.py", line 238, in request
    retries=urllib3.Retry(total=False, redirect=False, raise_on_redirect=False))
  File "/home/oliver/.local/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/home/oliver/.local/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/oliver/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 315, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/home/oliver/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 222, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.
```

Should I be changing the way that I instantiate the `Client`?

**Comment by ethan92429** [comment]
This was due to an issue with the documentation
